# Generated by Django 3.0.5 on 2021-04-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0003_auto_20210404_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
