# Generated by Django 3.0.5 on 2021-04-05 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0006_auto_20210405_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='description',
        ),
    ]
