# Generated by Django 3.0.5 on 2021-04-06 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0008_auto_20210406_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='description',
        ),
    ]
