# Generated by Django 3.0.5 on 2021-04-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0009_remove_title_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
