# Generated by Django 3.0.5 on 2021-04-06 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0010_title_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre_Title',
        ),
    ]
