# Generated by Django 3.0.5 on 2021-04-06 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0011_delete_genre_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='genre',
        ),
    ]
