# Generated by Django 3.0.5 on 2021-04-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0012_remove_title_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(related_name='genre', to='title.Genre'),
        ),
    ]
