# Generated by Django 3.0.5 on 2021-04-10 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0016_auto_20210410_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='description',
            new_name='bio',
        ),
    ]
