# Generated by Django 3.0.5 on 2021-04-17 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0017_auto_20210410_2042'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('title', 'author')},
        ),
    ]
